In [31]:
#import Libraries
import pandas as pd
import numpy as np
import re
import string


from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

import matplotlib.pyplot as plt
import seaborn as sns

LOAD THE DATASET

In [83]:
# Load the dataset
df = pd.read_csv("spam_dataset.csv", encoding='latin-1')

# display first 10 row in dataset
df.head(10)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...

In [84]:
# Basic information about dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   str
 1   Message   5572 non-null   str
dtypes: str(2)
memory usage: 87.2 KB

DATA CLEANING

In [91]:
# update dataset column names for easier debuging
df.columns = ['label', 'message']

In [92]:
# Convert labels to numeric
df['label'] = df['label'].map({'ham': 0, 'spam': 1})


#  Text cleaning function
# def clean_text(text):
#     text = text.lower()
#     text = re.sub(r'\d+', '', text)  # remove numbers
#     text = text.translate(str.maketrans('', '', string.punctuation))  # remove punctuation
#     text = text.strip()
#     return text

# df['message'] = df['message'].apply(clean_text)
df.head(10)

   label                                            message
0    NaN  go until jurong point crazy available only in ...
1    NaN                            ok lar joking wif u oni
2    NaN  free entry in  a wkly comp to win fa cup final...
3    NaN        u dun say so early hor u c already then say
4    NaN  nah i dont think he goes to usf he lives aroun...
5    NaN  freemsg hey there darling its been  weeks now ...
6    NaN  even my brother is not like to speak with me t...
7    NaN  as per your request melle melle oru minnaminun...
8    NaN  winner as a valued network customer you have b...
9    NaN  had your mobile  months or more u r entitled t...